data:
  test_path: "test.parquet"
  text_col: "text" # Cột chứa text gốc có dấu câu để test

model:
  lm_path: "jiayan.klm"
  cut_model_path: "cut_model"
  punc_model_path: "punc_model"

inference:
  batch_size: 1
